version: "3.9"
services:
  backend:
    env_file:
      - ./back/.env
    build:
      context: ./back
    container_name: insightly-backend
    ports:
      - "3001:3001"
    volumes:
      - ./back:/app
      - /app/node_modules  # <--- Ne pas écraser node_modules
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./front
    container_name: insightly-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules  # <--- idem
    environment:
      NODE_ENV: development
